### ISSUE TITLE
flake8 error at column 0 causes lsp to break

### ISSUE THREAD

**Issue by PookieBuns** [microsoft/vscode-flake8#141]
![image](https://user-images.githubusercontent.com/83051474/230890430-bc09aa5a-1c77-48d0-a9bf-65eabe3e67fc.png)
When I run linting for this file, it raises a value error of Position.character out of range in the log.

After modifying the source code for the lsp_server, adding a check
![image](https://user-images.githubusercontent.com/83051474/230890843-938cb62c-844d-41df-9e27-49bd56bf5802.png)
I found out the error thrown is caused by a column value of zero in the following log
![image](https://user-images.githubusercontent.com/83051474/230890916-05c86dcf-6ff4-4b2b-8727-d959980509f1.png)

I'm not sure exactly why the _parse_output_using_regex function subtracts by one, but this causes column 0 errors to break the lsp

I would suggest adding a conditional statement to set column to 0 if it is less than 0?

vscode version = 1.77.1
windows version = windows 11 education 22621.1105
flake version = 6.0.0 (flake8-annotations: 3.0.0, mccabe: 0.7.0, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.8.16 on Linux
flake8 v2023.4.0

**Comment by karthiknadig** [comment]
Flake8 typically has column offset of 1, (i.e, its columns start at 1). In the above case the fix is to ensure that the value never gets negative.

Note that, the issue here comes from a pluggin `flake8-annotation` that seems to be using 0 based columns.

**Comment by camilla122333** [comment]
can I work on this? ghc-osd

**Comment by hhalaby** [comment]
Hello, any updates on this issue ?

I tried using the flake8 extension and this is the error output I get every time I restart the server:

```
2023-11-02 10:50:18.879 [info] Server run command: /home/halaby/.venvs/shake/bin/python /home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/tool/lsp_server.py
2023-11-02 10:50:18.879 [info] Server: Start requested.
2023-11-02 10:50:19.220 [info] Traceback (most recent call last):
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/tool/lsp_server.py", line 251, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/libs/pygls/feature_manager.py", line 193, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

2023-11-02 10:50:19.263 [info] [Error - 10:50:19 AM] Server initialization failed.
2023-11-02 10:50:19.263 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:19.263 [info] [Info  - 10:50:19 AM] Connection to server got closed. Server will restart.
2023-11-02 10:50:19.263 [info] true
2023-11-02 10:50:19.263 [info] [Error - 10:50:19 AM] Flake8 client: couldn't create connection to server.
2023-11-02 10:50:19.263 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:19.598 [info] Traceback (most recent call last):
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/tool/lsp_server.py", line 251, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/libs/pygls/feature_manager.py", line 193, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

2023-11-02 10:50:19.644 [info] [Error - 10:50:19 AM] Server initialization failed.
2023-11-02 10:50:19.645 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:19.645 [info] [Info  - 10:50:19 AM] Connection to server got closed. Server will restart.
2023-11-02 10:50:19.645 [info] true
2023-11-02 10:50:19.645 [info] [Error - 10:50:19 AM] Flake8 client: couldn't create connection to server.
2023-11-02 10:50:19.645 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.099 [info] Traceback (most recent call last):
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/tool/lsp_server.py", line 251, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/libs/pygls/feature_manager.py", line 193, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

2023-11-02 10:50:20.150 [info] [Error - 10:50:20 AM] Server initialization failed.
2023-11-02 10:50:20.150 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.150 [info] [Info  - 10:50:20 AM] Connection to server got closed. Server will restart.
2023-11-02 10:50:20.150 [info] true
2023-11-02 10:50:20.150 [info] [Error - 10:50:20 AM] Flake8 client: couldn't create connection to server.
2023-11-02 10:50:20.150 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.150 [info] [Error - 10:50:20 AM] Restarting server failed
2023-11-02 10:50:20.150 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.555 [info] Traceback (most recent call last):
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/tool/lsp_server.py", line 251, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/libs/pygls/feature_manager.py", line 193, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

2023-11-02 10:50:20.603 [info] [Error - 10:50:20 AM] Server initialization failed.
2023-11-02 10:50:20.603 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.603 [info] [Info  - 10:50:20 AM] Connection to server got closed. Server will restart.
2023-11-02 10:50:20.603 [info] true
2023-11-02 10:50:20.603 [info] [Error - 10:50:20 AM] Flake8 client: couldn't create connection to server.
2023-11-02 10:50:20.603 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.603 [info] [Error - 10:50:20 AM] Restarting server failed
2023-11-02 10:50:20.603 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:20.965 [info] Traceback (most recent call last):
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/tool/lsp_server.py", line 251, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.8.0/bundled/libs/pygls/feature_manager.py", line 193, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

2023-11-02 10:50:21.012 [info] [Error - 10:50:21 AM] Server initialization failed.
2023-11-02 10:50:21.012 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:21.012 [info] [Error - 10:50:21 AM] The Flake8 server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-11-02 10:50:21.012 [info] [Error - 10:50:21 AM] Flake8 client: couldn't create connection to server.
2023-11-02 10:50:21.012 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-02 10:50:21.012 [info] [Error - 10:50:21 AM] Restarting server failed
2023-11-02 10:50:21.012 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 

```

**Comment by karthiknadig** [comment]
@hhalaby Your issue seems different from the one filed by the original author. Can you file a separate issue?

**Comment by PookieBuns** [comment]
I recall this issue already being fixed. This issue can be closed

**Comment by hhalaby** [comment]
@karthiknadig tried the pre-release version, still same error 

`"/home/halaby/.vscode-server/extensions/ms-python.flake8-2023.11.13101007/bundled/tool/lsp_server.py"`
